Mvp
NikitaLi/NewsApp pull request #1
Opened 2017-10-31 23:03 UTC by NikitaLi

2017-11-01 09:03 UTC, essiorh requested changes

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        WebView webView = findViewById(R.id.activity_news_details_webview);
не стоит в id view добавлять название layout. Нужно просто wb_details

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        progressBar = findViewById(R.id.activity_news_details_progressbar);
Здесь также: pb_details

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        presenter.loadArticlePage(index, webView);
Плохо передавать часть вью в презентер. Правильно будет вернуть результат во вью.

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +    public void onBindViewHolder(NewsViewHolder holder, @SuppressLint("RecyclerView") final int position) {
Чего тут сапресешь?

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +            ivImage = itemView.findViewById(R.id.card_news_image);
id должен быть: iv_card_news_image

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +            tvTitle = itemView.findViewById(R.id.card_news_title);
Здесь tv_card_news_title и далее по аналогии.

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsListActivity.java
> +        rvNews = findViewById(R.id.activity_main_recyclerview);
Здесь как в прошлой активити.

2017-11-01 09:03 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsListActivity.java
> +    public void showNewsList(GetArticlesResponse articlesResponse) {
Весь респонс передавать сюда нет смысла, можно просто List передать.

2017-11-01 10:07 UTC, NikitaLi commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +    public void onBindViewHolder(NewsViewHolder holder, @SuppressLint("RecyclerView") final int position) {
![image](https://user-images.githubusercontent.com/29162155/32270120-a92cf950-bf05-11e7-8b07-b586af6fb844.png)

2017-11-01 11:50 UTC, essiorh requested changes

2017-11-01 11:50 UTC, essiorh commented on .gitignore
> +.idea/modules.xml
папочка .idea должна быть все в гитигноре

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        if(getSupportActionBar() != null){
Пробел забыл

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        final ArticlePresenter presenter = new ArticlePresenter(this);
Лучше презентер сделать полем класса.

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        webView.setWebViewClient(new WebViewClient() {
Можно создание анонимного класса WebViewClient вынести в метод.

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +        webView.loadUrl(presenter.getArticleUrl(index));
Что это?

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticlePresenter.java
> +    String getArticleUrl(int index) {
методы презентера должны быть void

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +                        ArticleActivity.launch(view.getContext(), holder.getAdapterPosition());
Ну и решение)

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +            ivImage = itemView.findViewById(R.id.iv_card_news_image);
Получается у тебя view в разметке называется card news image, а поле класса с сылкой на эту вью всего лишь image.

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +            tvTitle = itemView.findViewById(R.id.tv_card_news_title);
с остальными полями та же история

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsListPresenter.java
> +                assert articlesResponse != null;
Тебе стоит прочитать, что делает assert, чтобы не писать подобного в будущем)

2017-11-01 11:50 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsListPresenter.java
> +                listView.showNewsList(newsList);
Капец, еле понял, что listView это интерфейс твоего фрагмента NewsList. Умеешь запутать))

2017-11-01 12:04 UTC, NikitaLi commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +                        ArticleActivity.launch(view.getContext(), holder.getAdapterPosition());
http://java-lang-programming.com/en/lints/2  отсюда взял

2017-11-01 12:05 UTC, NikitaLi commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +            ivImage = itemView.findViewById(R.id.iv_card_news_image);
думал что в этом контексте можно проще писать, без уточнений

2017-11-02 13:31 UTC, essiorh requested changes

2017-11-02 13:31 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +    final ArticleContract.Presenter presenter = new ArticlePresenter(this);
Перенести инициализацию в onCreate

2017-11-02 13:31 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +    WebView webView;
Нужно сделать private

2017-11-02 13:31 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleActivity.java
> +            getSupportActionBar().setTitle(NewsStore.getNewsArticles().get(index).getTitle());
Доступ к данным должен быть не во вью.

2017-11-02 13:31 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/article/ArticleContract.java
> +        void setTitleOfActionBar(int index);
Пустые строки между методами в интерфейсе должны быть по смыслу, как между полями класса.

2017-11-02 13:31 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsAdapter.java
> +        Glide.with(holder.ivCardImage.getContext()).load(newsArticle.getUrlToImage())
Перенести на новую строку вызов метода load

2017-11-02 13:31 UTC, essiorh commented on app/src/main/java/com/example/sony/newsapi/screen/newslist/NewsListPresenter.java
> +    private final NewsListView newsListView;
Назови поле просто view.

2017-11-02 16:01 UTC, essiorh approved these changes

2017-11-02 16:02 UTC, merged